### ISSUE TITLE
上线前问题清查

### ISSUE THREAD

**Issue by zxc0328** [Muxi-Studio/xueer_be#59]
1.课程列表页 按点赞排名和按评论排名是倒序的
2.课程列表页 列表中显示有评论的课点进去没有评论
3.热门评论API是目前全站的，应该是针对每一门课程的

**Comment by neo1218** [comment]
bug都修好了

+ 问题1: 不同数据库对null的处理不一样， postgresql默认把null放到开始，所以排序的时候都是反的
+ 问题2: 我这边测试数据库没有问题，显示评论的点进去都有评论，可能是部署数据库的数据问题
+ 问题3: 是我写代码的问题
